# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Bind-rbldnsdAccessor
version:      0.04
version_from: rbldnsdAccessor.pm
installdirs:  site
requires:
    Net::DNS::Codes:               0.09
    Net::DNS::ToolKit:             0.30

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
